### PR TITLE
ghcjs buildable version

### PR DESCRIPTION
**Pull request by buckie**
Big fan of the library, including the api upgrades from 0.3.5.5. I needed to build this via ghcjs and `cpphs` or `thyme.h` was blowing it up (linker errors, couldn't figure out which one). Regardless, this version built fine on OSX for ghcjs at the cost of the `lens` flag. Overall I dislike having a little custom lens as more and more people start using this lib but I do see the motivation as the build times increase. I think given `stack` and `new-build` that one time build hit is no longer so onerous.

### CODE REVIEW

**Comment by erikd** [comment]
@buckie Your PR doesn't build with ghc 7.6 of ghc 7.8:
```
src/Data/Thyme/Clock/TAI.hs:85:52:
    Not in scope: ‘mempty’
```
Versions of GHC earlier than 7.10 did not include `Data.Monoid` in the standard prelude. Fixing this probably involves adding something like:
```
#if __GLASGOW_HASKELL__ < 710
import Data.Monoid (mappend)
#endif
```
